name: Check Markdown and Examples
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm test
